# Generated by Django 5.0.6 on 2024-06-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0003_remove_product_variations_product_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=6, null=True, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='price'),
        ),
    ]
