# Generated by Django 5.0.6 on 2024-06-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0010_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='image'),
        ),
    ]
