# Generated by Django 5.0.6 on 2024-06-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image_cateogry',
            field=models.ImageField(blank=True, null=True, upload_to='photos/cateogry', verbose_name='image_cateogry'),
        ),
    ]
