# Generated by Django 5.0.6 on 2024-06-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0013_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
