# Generated by Django 5.0.6 on 2024-06-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0014_remove_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='items'),
        ),
    ]
