# Generated by Django 5.0.6 on 2024-06-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0016_cart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.IntegerField(blank=True, default=10, null=True, verbose_name='Shipping')),
                ('subtotal', models.IntegerField(blank=True, default=0, null=True, verbose_name='Subtotal')),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('cart', models.ManyToManyField(blank=True, null=True, to='shop_site.cart', verbose_name='Cart')),
            ],
        ),
    ]
