# Generated by Django 5.0.6 on 2024-06-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0017_cart_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total',
            new_name='total_item',
        ),
    ]
