# Generated by Django 5.0.6 on 2024-06-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0018_rename_total_cart_total_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart_summary',
        ),
    ]
