# Generated by Django 5.0.6 on 2024-06-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_site', '0019_delete_cart_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Subtotal',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='subtotal'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='shipping'),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_summary',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='total_summary'),
        ),
    ]
